<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="plato_robot">
<xacro:include filename="$(find plato_description)/urdf/parameters.xacro"/>
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so" >
            <commandTopic>${command_topic_name}</commandTopic>
            <odometryTopic>${odometry_topic_name}</odometryTopic>
            <odometryFrame>${odometry_topic_name}</odometryFrame>
            <robotBaseFrame>${base_name}</robotBaseFrame>
            <publishWheelTF>true</publishWheelTF>
            <publishWheelJointState>true</publishWheelJointState>
            <legacyMode>false</legacyMode>
            <wheelSeparation>${wheel_distance}</wheelSeparation>
            <wheelDiameter>${wheel_radius*2}</wheelDiameter>
            <wheelAcceleration>${wheel_acceleration_gazebo}</wheelAcceleration>
            <wheelTorque>${wheel_torque_gazebo}</wheelTorque>
            <updateRate>${update_rate_gazebo}</updateRate>
            <leftJoint>${left_wheel_joint_name}</leftJoint>
            <rightJoint>${right_wheel_joint_name}</rightJoint>
            <publishTf>1</publishTf>
        </plugin>
    </gazebo>

    <gazebo reference="chassis">
        <material>Gazebo/Yellow</material>
    </gazebo>
    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="caster_wheel">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="center_bumper">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="left_bumper">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="right_bumper">
        <material>Gazebo/Black</material>
    </gazebo>


</robot>
